// src/wrappers/angular/kds-button.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '../../components/kds-button';

@Component({
  selector: 'kds-button-ng',
  standalone: true,
  template: `
    <kds-button
      [attr.appearance]="appearance"
      [attr.state]="state"
      [attr.has-icon]="hasIcon ? '' : null"
      [attr.label]="label"
      [attr.icon]="icon"
      [attr.href]="href"
      [attr.type]="type"
      (kds-click)="onKdsClick($event)">
      <ng-content></ng-content>
    </kds-button>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class KdsButtonComponent {
  @Input() appearance: 'filled' | 'outlined' | 'text' | 'elevated' | 'tonal' = 'filled';
  @Input() state: 'enabled' | 'disabled' | 'hovered' | 'focused' | 'pressed' = 'enabled';
  @Input() hasIcon: boolean = false;
  @Input() label: string = '';
  @Input() icon: string = 'add';
  @Input() href: string | null = null;
  @Input() type: 'button' | 'submit' | 'reset' = 'button';

  @Output('kds-click') kdsClick = new EventEmitter<CustomEvent>();

  constructor(private el: ElementRef) {}

  onKdsClick(event: Event) {
    this.kdsClick.emit(event as CustomEvent);
  }
}

// src/wrappers/react/KdsButton.tsx
import React, { forwardRef, useLayoutEffect, useRef } from 'react';
import '../../components/kds-button';

// Extend the global HTMLElementTagNameMap to include kds-button in JSX
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'kds-button': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
        'appearance'?: 'filled' | 'outlined' | 'text' | 'elevated' | 'tonal';
        'state'?: 'enabled' | 'disabled' | 'hovered' | 'focused' | 'pressed';
        'has-icon'?: boolean | string;
        'label'?: string;
        'icon'?: string;
        'href'?: string;
        'type'?: string;
      };
    }
  }
}

export interface KdsButtonProps extends React.HTMLAttributes<HTMLElement> {
  appearance?: 'filled' | 'outlined' | 'text' | 'elevated' | 'tonal';
  state?: 'enabled' | 'disabled' | 'hovered' | 'focused' | 'pressed';
  hasIcon?: boolean;
  label?: string;
  icon?: string;
  href?: string;
  type?: 'button' | 'submit' | 'reset';
  onKdsClick?: (e: CustomEvent) => void;
}

export const KdsButton = forwardRef<HTMLElement, KdsButtonProps>(
  ({ onKdsClick, hasIcon, ...props }, ref) => {
    const elementRef = useRef<HTMLElement>(null);
    const combinedRef = (node: HTMLElement) => {
      // @ts-ignore
      elementRef.current = node;
      if (typeof ref === 'function') ref(node);
      else if (ref) (ref as React.MutableRefObject<HTMLElement | null>).current = node;
    };

    useLayoutEffect(() => {
      const element = elementRef.current;
      if (!element || !onKdsClick) return;

      const handleEvent = (e: Event) => onKdsClick(e as CustomEvent);
      element.addEventListener('kds-click', handleEvent);
      return () => {
        element.removeEventListener('kds-click', handleEvent);
      };
    }, [onKdsClick]);

    return (
      <kds-button
        ref={combinedRef}
        has-icon={hasIcon}
        {...props}
      />
    );
  }
);
